### ISSUE TITLE
Windows install

### ISSUE THREAD

**Issue by lypt123** [ladaapp/lada#14]
Did according to the instructions step by step then have an error:
After
`python -m pip install -e '.[basicvsrpp,gui]'`
returns
`ERROR: '.[basicvsrpp,gui]' is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).`

**Comment by ladaapp** [comment]
@seatv is currently also trying to build it on windows, maybe you can check his notes here https://github.com/ladaapp/lada/issues/12

Not sure about the error you're seeing but this doesn't look in any way windows-specific. Are you sure you're in the root directory of the cloned repo (`setup.py` file must be there. It  defines those extras you're trying to install here...)

**Comment by lypt123** [comment]
```
(base) C:\Windows\System32>cd .venv/lada

(base) C:\Windows\System32\.venv\lada>dir

08.12.2024  15:17    <DIR>          .
08.12.2024  15:17    <DIR>          ..
08.12.2024  15:17               138 .gitignore
08.12.2024  15:17    <DIR>          assets
08.12.2024  15:17    <DIR>          configs
08.12.2024  15:17             8 547 create_mosaic_detection_image_dataset.py
08.12.2024  15:17             7 810 create_mosaic_edge_detection_image_dataset.py
08.12.2024  15:17            33 567 create_mosaic_removal_video_dataset.py
08.12.2024  15:17             5 491 create_mosaic_removal_video_test_dataset.py
08.12.2024  15:17    <DIR>          flatpak
08.12.2024  15:17    <DIR>          labelme
08.12.2024  15:17    <DIR>          lada
08.12.2024  15:17            34 920 LICENSE.md
08.12.2024  15:17    <DIR>          model_weights
08.12.2024  15:17    <DIR>          patches
08.12.2024  15:17            14 100 README.md
08.12.2024  15:17             3 808 run_bj_classifier.py
08.12.2024  15:17             1 136 setup.py
08.12.2024  15:17             3 192 train_basicvsrpp.py
08.12.2024  15:17             2 685 train_bj_classifier.py
08.12.2024  15:17            16 024 train_deepmosaics.py
08.12.2024  15:17            14 241 train_rvrt.py
08.12.2024  15:17            10 820 train_tecogan.py
08.12.2024  15:17             1 824 validate_basicvsrpp.py
08.12.2024  15:17             1 407 validate_tecogan.py
08.12.2024  15:17             3 361 view-clean-mosaic.py

(base) C:\Windows\System32\.venv\lada>python -m pip install -e '.[basicvsrpp,gui]'
ERROR: '.[basicvsrpp,gui]' is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
```
I read @seatv topic however there was normal `Obtaining file:///D:/venv/lada` and no such issue. So I decided to start new topic.  If you wish I can just move there.

**Comment by ladaapp** [comment]
Hmm maybe Windows doesn't like the single quotes there? try to replace it with double quotes.
Otherwise make sure you're using Python 3.12 and that pip is up-to-date `pip install --upgrade pip setuptools`. Maybe it doesn't like the relative path? Try to replace the `.` with the full path.
Using `C:\Windows\System32` as your working directory seems weird -> try to clone the project into you user directory not in this system directory. Also the virtual environment should be created in the root your cloned repository not the other way around.

**Comment by lypt123** [comment]
Ok, installed again in different disc and created virtual environment in \lada\. Error shows up again and it is just double quotes. 
Ran `pacman -S mingw-w64-x86_64-gobject-introspection` via MSYS2 but have same error as @seatv
`(venv) (base) F:\lada>python -m pip install -e ".[basicvsrpp,gui]"
Obtaining file:///F:/lada
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting torch (from lada==0.2.5.dev0)
  Using cached torch-2.5.1-cp312-cp312-win_amd64.whl.metadata (28 kB)
Collecting ultralytics (from lada==0.2.5.dev0)
  Using cached ultralytics-8.3.48-py3-none-any.whl.metadata (35 kB)
Requirement already satisfied: numpy in f:\lada\venv\lib\site-packages (from lada==0.2.5.dev0) (2.2.0)
Requirement already satisfied: opencv-python in f:\lada\venv\lib\site-packages (from lada==0.2.5.dev0) (4.10.0.84)
Collecting tqdm (from lada==0.2.5.dev0)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting av (from lada==0.2.5.dev0)
  Using cached av-14.0.1-cp312-cp312-win_amd64.whl.metadata (4.6 kB)
Requirement already satisfied: mmengine==0.10.5 in f:\lada\venv\lib\site-packages (from lada==0.2.5.dev0) (0.10.5)
Requirement already satisfied: mmcv in f:\lada\venv\lib\site-packages (from lada==0.2.5.dev0) (2.2.0)
Collecting pycairo (from lada==0.2.5.dev0)
  Using cached pycairo-1.27.0-cp312-cp312-win_amd64.whl.metadata (2.3 kB)
Collecting PyGObject (from lada==0.2.5.dev0)
  Using cached pygobject-3.50.0.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      + meson setup C:\Users\LPETR\AppData\Local\Temp\pip-install-delqgj5b\pygobject_09c2fc5151ad4e129597bc71682b61e9 C:\Users\LPETR\AppData\Local\Temp\pip-install-delqgj5b\pygobject_09c2fc5151ad4e129597bc71682b61e9\.mesonpy-f7wnpxzg -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dtests=false -Dwheel=true --wrap-mode=nofallback --native-file=C:\Users\LPETR\AppData\Local\Temp\pip-install-delqgj5b\pygobject_09c2fc5151ad4e129597bc71682b61e9\.mesonpy-f7wnpxzg\meson-python-native-file.ini
      The Meson build system
      Version: 1.6.0
      Source dir: C:\Users\LPETR\AppData\Local\Temp\pip-install-delqgj5b\pygobject_09c2fc5151ad4e129597bc71682b61e9
      Build dir: C:\Users\LPETR\AppData\Local\Temp\pip-install-delqgj5b\pygobject_09c2fc5151ad4e129597bc71682b61e9\.mesonpy-f7wnpxzg
      Build type: native build
      Project name: pygobject
      Project version: 3.50.0
      WARNING: Failed to activate VS environment: Could not parse vswhere.exe output

      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] Не удается найти указанный файл"
      Running `cl /?` gave "[WinError 2] Не удается найти указанный файл"
      Running `cc --version` gave "[WinError 2] Не удается найти указанный файл"
      Running `gcc --version` gave "[WinError 2] Не удается найти указанный файл"
      Running `clang --version` gave "[WinError 2] Не удается найти указанный файл"
      Running `clang-cl /?` gave "[WinError 2] Не удается найти указанный файл"
      Running `pgcc --version` gave "[WinError 2] Не удается найти указанный файл"

      A full log can be found at C:\Users\LPETR\AppData\Local\Temp\pip-install-delqgj5b\pygobject_09c2fc5151ad4e129597bc71682b61e9\.mesonpy-f7wnpxzg\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(venv) (base) F:\lada>`

**Comment by lypt123** [comment]
Looks like I can't even activate visualstudio or just did something wrong

**Comment by ladaapp** [comment]
Your error is not the same that seatv posted. In his logs you can see that c compiler/linker checks run through without issues.

But I'm just wondering why you and @seatv need to compile the PyGobject package in the first place. Would have expected that pip will just download the wheel from PyPi (at least that how it works if you install it via pip on linux). Maybe they don't provide them for Windows? Not sure

Double check that you are in an msys2 environment.
The `python` / `pip` binaries in msys2 are not the same as the official python installers.
https://www.msys2.org/docs/python/

**Comment by lypt123** [comment]
Well, updated msys2 via https://www.msys2.org/docs/updating/ and checked. In sum, I just have error `..\meson.build:31:9: ERROR: Dependency 'gobject-introspection-1.0' is required but not found` as @seatv had even with `pacman -S mingw-w64-x86_64-gobject-introspection`. I'll just move [there](https://github.com/ladaapp/lada/issues/12) and ask about it.
