### ISSUE TITLE
Linix Mint 0S

### ISSUE THREAD

**Issue by leoRubberduck** [ladaapp/lada#2]
Hi again,

I have replaced my windows 11 and I am now running Linix Mint. Has flatpak version 1.14 built in 

I tried to install it via the instructions and i get:
desktop:~$ sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
[sudo] password for leo:              
desktop:~$ flatpak install flathub io.github.ladaapp.lada
Looking for matches…
error: Nothing matches io.github.ladaapp.lada in remote flathub
desktop:~$ 

Also it advised me to check the flathub app and search for lada and nothing was there to confirm exsistence

**Comment by leoRubberduck** [comment]
leo@leo-desktop:~$ flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install --user -y flathub org.flatpak.Builder
flatpak run org.flatpak.Builder --force-clean --sandbox --user --install --install-deps-from=flathub flatpak/build flatpak/io.github.ladaapp.lada.yaml
Looking for matches…
Required runtime for org.flatpak.Builder/x86_64/stable (runtime/org.freedesktop.Sdk/x86_64/24.08) found in remote flathub

org.flatpak.Builder permissions:
    network       devel       file access [1]       dbus access [2]

    [1] /tmp, /var/lib/flatpak, host, xdg-data/flatpak
    [2] org.freedesktop.Flatpak


        ID                                         Branch     Op Remote  Download
 1. [✓] org.freedesktop.Platform.GL.default        24.08      i  flathub 146.5 MB / 146.8 MB
 2. [✓] org.freedesktop.Platform.GL.default        24.08extra i  flathub  22.7 MB / 146.8 MB
 3. [✓] org.freedesktop.Platform.GL.nvidia-550-120 1.4        i  flathub 307.9 MB / 308.0 MB
 4. [✓] org.freedesktop.Platform.openh264          2.4.1      i  flathub 920.7 kB / 976.5 kB
 5. [✓] org.freedesktop.Sdk.Locale                 24.08      i  flathub  18.6 kB / 385.0 MB
 6. [✓] org.gtk.Gtk3theme.Mint-Y-Aqua              3.22       i  flathub  72.8 kB / 114.8 kB
 7. [✓] org.freedesktop.Sdk                        24.08      i  flathub 535.0 MB / 615.6 MB
 8. [✓] org.flatpak.Builder                        stable     i  flathub  42.6 MB / 47.6 MB

Installation complete.
Can't load 'flatpak/io.github.ladaapp.lada.yaml': Failed to open file “/home/leo/flatpak/io.github.ladaapp.lada.yaml”: No such file or directory

**Comment by ladaapp** [comment]
The errors in your first post are expected as the app is not yet up on flathub as I'm still in the reviewing/submission process over at their repository. (Thought I mentioned this in the README already :thinking: )

The error in your second post `Failed to open file “/home/leo/flatpak/io.github.ladaapp.lada.yaml”` indicates that you're maybe not in the correct directory as it cannot find `flatpak/io.github.ladaapp.lada.yaml`.
1) Clone the lada repo
2) cd into the cloned repo
3) now run the build command: `flatpak run org.flatpak.Builder --force-clean --sandbox --user --install --install-deps-from=flathub flatpak/build flatpak/io.github.ladaapp.lada.yaml`

**Comment by leoRubberduck** [comment]
Thanks works really good. 

Also tried VR mp4 and got this error :+1: 
ile "/app/lib/python3.12/site-packages/lada/lib/video_utils.py", line 227, in get_video_meta_data
    raise Exception(f"error running ffprobe: {err.strip()}. Code: {p.returncode}, cmd: {cmd}")
Exception: error running ffprobe: b''. Code: 1, cmd: ['ffprobe', '-v', 'quiet', '-output_format', 'json', '-select_streams', 'v', '-show_streams', '-show_format

but normal videos work just fine

**Comment by ladaapp** [comment]
Try to run the `ffprobe` command you see there on the command line without the `-v quiet` option. Should give you a bit more clues what's going wrong

**Comment by leoRubberduck** [comment]
Yeah i got the output from that commend and got GPT to analyze it :+1: 

The output here shows that ffprobe successfully analyzed the MP4 file, so the issue likely isn’t with ffprobe itself but rather with how the Lada app is using ffprobe for VR files. Since ffprobe can handle standard videos but fails on VR-specific ones, it’s possible that VR MP4s have additional metadata or format-specific details that aren’t handled well by the Lada app's current implementation.

Here are a few potential next steps:

    Verify VR Metadata: VR files sometimes contain specialized metadata (such as spatial or stereoscopic information) that ffprobe doesn’t extract by default. You could try running ffprobe with more detailed metadata options, such as:

    bash

ffprobe -v error -show_entries format -show_entries stream_tags -show_format_tags -print_format json "VR_video.mp4"

Convert the VR Video: Sometimes re-encoding VR videos can help make the metadata more accessible. Try converting the VR video to a standard MP4 format as a test:

bash

ffmpeg -i "VR_video.mp4" -c:v copy -c:a copy "converted_video.mp4"

Then try running it through the Lada app to see if the issue persists.

Inspect the Lada App’s video_utils.py: Since the error points to video_utils.py in Lada, it’s possible that the code doesn’t account for certain metadata structures found in VR files. You could try adjusting the code to capture a broader set of metadata fields or error handling for VR-specific issues.

**Comment by leoRubberduck** [comment]
I will work on the VR aspect tomorrow. It will be good because so far nobody has done removal on VR content. It should not be that hard really.

**Comment by ladaapp** [comment]
Submission to flathub went through so no more need to build the flatpak yourself.
