### ISSUE TITLE
Can you introduce the training steps in detail?

### ISSUE THREAD

**Issue by xiaoniao231** [ladaapp/lada#6]

**Comment by ladaapp** [comment]
You'll need to provide more details, which step from the README is unclear?

For example:
* Which model do you want to train (mosaic restoration, mosaic detection, nsfw detction?)
* Were you able to create the dataset?

You should make yourself familiar with [Ultralytics](https://docs.ultralytics.com/) if you want to train mosaic or nsfw detction models.

If you want to train the mosaic restoration model then check out [MMEngine](https://mmengine.readthedocs.io/en/latest/) and [MMagic](https://mmagic.readthedocs.io/en/latest/).

**Comment by xiaoniao231** [comment]
Ok, I used your software on the computer of Ubuntu system, and the effect is very good. It feels much better than javplayer. By the way, how much graphics memory is needed to train the model?

**Comment by ladaapp** [comment]
I trained it on a GPU with 24G of VRAM and that is what the committed config files are optimized for.
But you can adjust `batch_size` and `num_frames` in the config file if have less or more VRAM available.

**Comment by xiaoniao231** [comment]
Ok, thank you.

**Comment by ladaapp** [comment]
I've added a bit more details to the Datasets and Training sections of the README

**Comment by xiaoniao231** [comment]
Thank you very much for what you have done. It's hard work.



---Original---
From: ***@***.***&gt;
Date: Fri, Dec 6, 2024 01:07 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ladaapp/lada] Can you introduce the training steps in detail?(Issue #6)




 
I've added a bit more details to the Datasets and Training sections of the README
